# Data Cleaning on Retail Sales Dataset

## Objective

The objective of this project is to clean the Vrinda Store retail sales dataset by identifying and handling missing values, duplicate records, incorrect data types, inconsistent formatting, and invalid values. A clean dataset improves the quality of analysis and helps generate reliable business insights.


## Tools & Technologies

- Python
- Pandas
- NumPy
- Jupyter Notebook

In [1]:
# Import Libraries

import numpy as np
import pandas as pd

### Loading the Dataset

In [3]:
df = pd.read_excel("../../DataAnalytics-L1-EDARetailSales/dataset/sales_dataset.xlsx")
df.head()

,index,Order ID,Cust ID,Gender,Age,Date,Status,Channel,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Women,44,2022-12-04,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Women,29,2022-12-04,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Women,67,2022-12-04,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Women,20,2022-12-04,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Women,62,2022-12-04,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False

In [3]:
#Shape
df.shape

(31047, 19)

In [4]:
# Columns
df.columns

Index(['index', 'Order ID', 'Cust ID', 'Gender', 'Age', 'Date', 'Status',
       'Channel ', 'SKU', 'Category', 'Size', 'Qty', 'currency', 'Amount',
       'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'B2B'],
      dtype='object')

In [6]:
# Data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             31047 non-null  int64
 1   Order ID          31047 non-null  object
 2   Cust ID           31047 non-null  int64
 3   Gender            31047 non-null  object
 4   Age               31047 non-null  int64
 5   Date              31047 non-null  datetime64[ns]
 6   Status            31047 non-null  object
 7   Channel           31047 non-null  object
 8   SKU               31047 non-null  object
 9   Category          31047 non-null  object
 10  Size              31047 non-null  object
 11  Qty               31047 non-null  object
 12  currency          31047 non-null  object
 13  Amount            31047 non-null  int64
 14  ship-city         31047 non-null  object
 15  ship-state        31047 non-null  object
 16  ship-postal-code  31047 non-null  int64
 17  ship-country      31047 non-null  object
 18  B2B               31047 non-null  bool
dtypes: bool(1), datetime64[ns](1), int64(5), object(12)
memory usage: 4.3+ MB

In [7]:
# Missing Values
df.isnull().sum()

index               0
Order ID            0
Cust ID             0
Gender              0
Age                 0
Date                0
Status              0
Channel             0
SKU                 0
Category            0
Size                0
Qty                 0
currency            0
Amount              0
ship-city           0
ship-state          0
ship-postal-code    0
ship-country        0
B2B                 0
dtype: int64

#### Observation

The dataset was checked for missing values after cleaning. No missing values remain in the cleaned dataset.

In [8]:
# Duplicate values
df.duplicated().sum()

np.int64(0)

#### Observation

The dataset was checked for duplicate records. No duplicate rows were found after the cleaning process.

In [9]:
# Remove extra spaces from Column names
df.columns = df.columns.str.strip()

In [12]:
# Convert date column 
df['Date'] = pd.to_datetime(df['Date'])

In [13]:
df['Date'].dtype

dtype('<M8[ns]')

In [18]:
# Check negative revenue
df[df['Amount'] < 0]

Empty DataFrame
Columns: [index, Order ID, Cust ID, Gender, Age, Date, Status, Channel, SKU, Category, Size, Qty, currency, Amount, ship-city, ship-state, ship-postal-code, ship-country, B2B]
Index: []

In [21]:
# Check invalid quantity

# print(df['Qty'].value_counts())
df['Qty'] = df['Qty'].replace({"One" : 1,
                              "Two" : 2})
df['Qty']=pd.to_numeric(df['Qty'])

df[df['Qty'] < 0]

Empty DataFrame
Columns: [index, Order ID, Cust ID, Gender, Age, Date, Status, Channel, SKU, Category, Size, Qty, currency, Amount, ship-city, ship-state, ship-postal-code, ship-country, B2B]
Index: []

In [26]:
df['Gender'] = df['Gender'].str.title()

#standardize the values in the **Gender** column by replacing different representations of the same gender with a consistent format.

df['Gender'] = df['Gender'].replace({
    'M': 'Men',
    'm': 'Men',
    'Man': 'Men',
    'W': 'Women',
    'w': 'Women',
    'Woman': 'Women'
})

In [27]:
df['Gender'].value_counts()

Gender
Women    21553
Men       9494
Name: count, dtype: int64

In [28]:
#Standardize Category
df['Category'] = df['Category'].str.title()

In [29]:
#Standardize Channel
df['Channel'] = df['Channel'].str.title()

In [30]:
#Standardize state
df['ship-state'] = df['ship-state'].str.title()

In [31]:
# Check outliers
df[['Age','Qty','Amount']].describe()

                Age           Qty        Amount
count  31047.000000  31047.000000  31047.000000
mean      39.496570      1.006120    682.074822
std       15.117233      0.094088    268.582173
min       18.000000      1.000000    229.000000
25%       28.000000      1.000000    486.000000
50%       37.000000      1.000000    646.000000
75%       47.000000      1.000000    794.000000
max       78.000000      5.000000   3036.000000

In [33]:
# Final missing value check
df.isnull().sum()

index               0
Order ID            0
Cust ID             0
Gender              0
Age                 0
Date                0
Status              0
Channel             0
SKU                 0
Category            0
Size                0
Qty                 0
currency            0
Amount              0
ship-city           0
ship-state          0
ship-postal-code    0
ship-country        0
B2B                 0
dtype: int64

In [36]:
# Final duplicate value check
df.duplicated().sum()

np.int64(0)

In [37]:
# Final shape
df.shape

(31047, 19)

### Observation

The final dataset contains all valid records and is ready for further analysis and visualization.

### Summary

The following data cleaning operations were performed:

- Removed unnecessary spaces from column names.
- Verified missing values.
- Checked duplicate records.
- Converted the Date column to datetime format.
- Standardized categorical values where required.
- Checked numerical columns for invalid values.
- Verified the cleaned dataset.

### Conclusion

The Vrinda Store dataset was successfully cleaned and prepared for further analysis. The dataset was checked for missing values, duplicate records, incorrect data types, and inconsistent categorical values. After validation, the cleaned dataset is accurate, consistent, and ready for exploratory data analysis and customer segmentation.